### ISSUE TITLE
Pawn 128k

### ISSUE THREAD

**Issue by TomDDG** [skoolkid/t2sfiles#2]
https://worldofspectrum.net/pub/sinclair/games/p/PawnThe.tzx.zip
pawn-the-128k.z80
--tape-name "The Pawn.tzx"
--tape-sum 67dfbd6466335c61534289a8767ae68f
--start 25556
--sim-load-config machine=128
--sim-load-config accelerator=bleepload

**Comment by skoolkid** [comment]
Thanks! Added in aec67c46789d8caafa029fd155ab5bf5a1a3e675.

I left `-128k` off the name because it looks like The Pawn is 128K only (i.e. no 48K version). If that's not the case, let me know.

**Comment by TomDDG** [comment]
It is 128k only

**Comment by TomDDG** [comment]
Also Addams Family is 128k only as well
