### ISSUE TITLE
Tai-Pan 128k version crashes on load

### ISSUE THREAD

**Issue by TomDDG** [skoolkid/t2sfiles#4]
https://worldofspectrum.net/pub/sinclair/games/t/Tai-Pan.tzx.zip

Trying to convert 128k version, skoolkit creates the Z80 fine but then trying to load the Z80 in an emulator just resets the Spectrum. The TZX loads fine in FUSE and I can create a snapshot in the emulator which works.

**Comment by skoolkid** [comment]
This game checks the state of the AY chip after loading - possibly as a protection mechanism. Anyway, I've just added support to tap2sna.py for tracking and recording AY state, so it should work now. Let me know.

**Comment by skoolkid** [comment]
There is now a working t2s file for Tai-Pan 128K [in this repository](https://github.com/skoolkid/t2sfiles/blob/master/t2s/t/tai-pan-128k.t2s).
